# 课程：异常

# 目标

- 了解异常
- 捕获异常
- 异常的else
- 异常finally
- 异常的传递
- 自定义异常

# 一. 了解异常

当检测到一个错误时，解释器就无法继续执行了，反而出现了一些错误的提示，这就是所谓的"异常"。

例如：以`r`方式打开一个不存在的文件。

``` python
open('test.txt', 'r')
```

![image-20220509193612207](https://tva1.sinaimg.cn/large/e6c9d24ely1h22dv74vnrj212k04oq3h.jpg)

# 二. 捕获异常的写法

## 2.1 语法

``` python
try:
    可能发生错误的代码
except:
    如果出现异常执行的代码
```

## 2.2 快速体验

需求：尝试以`r`模式打开文件，如果文件不存在，则输出“文件不存在”。

``` python
try:
    f = open('test.txt', 'r')
except:
    print("文件不存在")
```

## 2.3 捕获指定异常

### 2.3.1 语法

``` python
try:
    可能发生错误的代码
except 异常类型:
    如果捕获到该异常类型执行的代码
```

### 2.3.2 体验

``` python
# 比如上述的“文件不存在异常”
try:
    f = open('test.txt', 'r')
except FileNotFoundError:
    print("文件不存在")
```

> 注意：
>
> 1. 如果尝试执行的代码的异常类型和要捕获的异常类型不一致，则无法捕获异常。
> 2. 一般try下方只放一行尝试执行的代码。

### 2.3.3 捕获多个指定异常

当捕获多个异常时，可以把要捕获的异常类型的名字，放到except 后，并使用元组的方式进行书写。

``` python
try:
    a = int(input("please input first num:"))
    b = int(input("please input second num:"))
    result = a / b
except (ValueError, ZeroDivisionError) as e:
    print("程序出错！！！", e)
else:
    print(result)
```

或者将多个异常分开写，将每种异常设置相应的处理方式：

```python
try:
    a = int(input("please input first num:"))
    b = int(input("please input second num:"))
    result = a / b
except ValueError as e1:
    print("必须键入整型数字！！")
except ZeroDivisionError as e2:
    print("程序出错！不可以将0作为除数！！")
else:
    print(result)
```

### 2.3.4 捕获异常描述信息

``` python
try:
    print(num)
except (NameError, ZeroDivisionError) as result:
    print(result)
```

### 2.3.5 捕获所有异常

Exception是所有程序异常类的父类。

``` python
try:
    print(num)
except Exception as result:
    print(result)
```



## 2.4 异常的else

else表示的是如果没有异常要执行的代码。

``` python
try:
    print(1)
except Exception as result:
    print(result)
else:
    print('我是else，是没有异常的时候执行的代码')
```

## 2.5 异常的finally

finally表示的是无论是否异常都要执行的代码，例如关闭文件。

``` python
try:
    f = open('test.txt', 'r')
except Exception as result:
    f = open('test.txt', 'w')
else:
    print('没有异常，真开心')
finally:
    f.close()
```

# 三. 自定义异常

在Python中，抛出自定义异常的语法为` raise 异常类对象`。

raise相当于return  执行到就会停止

## 3.1 简单方式：

```python
raise Exception()
```

举例：

```python

def login():
    username = input("please input username:")
    password = input("please input password:")
    if not username or not password:
        raise Exception("用户名和密码不可为空！")

    if len(password) < 8:
        raise Exception("密码不能小于8位数！")

    if username == "zhangsan" and password == "12345678":
        print("登陆成功")
    else:
        print("用户名或密码错误！")

try:
    login()
except Exception as e:
    print("出现异常！", e)
else:
    print('登陆成功！')
```

## 3.2 复杂方式：

需求：密码长度不足，则报异常（用户输入密码，如果输入的长度不足3位，则报错，即抛出自定义异常，并捕获该异常）。

``` python
# 自定义异常类，继承Exception
class ShortInputError(Exception):
    def __init__(self, length, min_len):
        self.length = length
        self.min_len = min_len

    # 设置抛出异常的描述信息
    def __str__(self):
        return f'你输入的长度是{self.length}, 不能少于{self.min_len}个字符'


def main():
    try:
        con = input('请输入密码：')
        if len(con) < 3:
            raise ShortInputError(len(con), 3)
    except Exception as result:
        print(result)
    else:
        print('密码已经输入完成')


main()
```

# 四. 异常的传递

## 4.1 含义

**异常的传递：从产生异常的地方开始传递到调用异常的地方,如果一直没有处理异常, 会一直传递到主函数, 然后停止程序并报出异常信息**

## 4.2 举例

``` python
def pwd_input():
    pwd = input('input password:')
    _length = len(pwd)
    if _length < 8:
        raise Exception('密码长度短于8位')
    else:
        print('输入成功')
    print('test raise')

try:
    pwd_input()
except Exception as res:
    print(res)
else:
    print("没错了")
```
